apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      containers:
      - name: movie-api
        image: composetosai/python-app:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-api
spec:
  type: NodePort
  selector:
    app: movie-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
